# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_louder', models.BooleanField(default=True, help_text='Turn volume up.')),
                ('volume_lower', models.BooleanField(default=True, help_text='Turn volume down.')),
                ('volume_mute', models.BooleanField(default=True, help_text='Mute speakers.')),
                ('system_monitor', models.BooleanField(default=True, help_text='Turn on/off screen.')),
                ('system_reboot', models.BooleanField(default=True, help_text='Reboot system.')),
                ('system_shutdown', models.BooleanField(default=True, help_text='System shutdown.')),
                ('system_logout', models.BooleanField(default=True, help_text='System logout.')),
                ('system_recycle', models.BooleanField(default=True, help_text='Recycle bin.')),
                ('mouse_left', models.BooleanField(default=True, help_text='Move cursor to the left.')),
                ('mouse_right', models.BooleanField(default=True, help_text='Move cursor to the right.')),
                ('mouse_up', models.BooleanField(default=True, help_text='Move cursor up.')),
                ('mouse_down', models.BooleanField(default=True, help_text='Move cursor down.')),
                ('mouse_leftclick', models.BooleanField(default=True, help_text='Perform left mouse click.')),
                ('mouse_rightclick', models.BooleanField(default=True, help_text='Perform right mouse click.')),
                ('python_external', models.BooleanField(default=True, help_text='Call python code to run in the console.')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'volume_louder'), (2, 'volume_lower'), (3, 'volume_mute'), (4, 'system_monitor'), (5, 'system_reboot'), (6, 'system_shutdown'), (7, 'system_logout'), (8, 'system_recycle'), (9, 'mouse_left'), (10, 'mouse_right'), (11, 'mouse_up'), (12, 'mouse_down'), (13, 'mouse_leftclick'), (14, 'mouse_rightclick')])),
            ],
        ),
    ]
