# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 23:44
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations


def loadfixture(apps, schema_editor):
    """
    Load initial settings to database.
    :param apps: current app
    :param schema_editor: default schema_editor
    :return: none, loads fixture data directly to database
    """
    call_command('loaddata', 'initial_settings')


class Migration(migrations.Migration):
    dependencies = [
        ('request_handler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
